export const LOCATION_ITEMS = [
  {
    id: "andheri",
    title: "DBSW Workspace, Andheri",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "Kanakia Wall street, Chakala, Andheri Kurla Road, Andheri East, Mumbai, Maharashtra 400093",
    phone: "02240779100",
    city: "mumbai",
    group: "workspace",
    marker: { xPct: 58, yPct: 54 },
  },
  {
    id: "fort",
    title: "DBSW House, Fort",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "DBSW House, Prescott Road,",
    phone: "02240779100",
    city: "mumbai",
    group: "house",
    marker: { xPct: 52, yPct: 62 },
  },
  {
    id: "one-world-center",
    title: "DBSW Workspace, One world Center",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "9th Floor Tower 1, One World Center Senapati Bapat Marg, Lower Parel, Mumbai 400013",
    phone: "02240779100",
    city: "mumbai",
    group: "workspace",
    marker: { xPct: 55, yPct: 70 },
  },
  {
    id: "nariman-point",
    title: "DBSW Workspace, Nariman Point",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "Raheja Chambers, 2nd Floor, Nariman Point, Mumbai 400021",
    phone: "02240779100",
    city: "mumbai",
    group: "workspace",
    marker: { xPct: 50, yPct: 66 },
  },
  {
    id: "donear-one-twelve",
    title: "Align by DBSW, Donear one Twelve",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "Donear One Twelve, Road no 13, MIDC Industrial Estate, Andheri East",
    phone: "02240779100",
    city: "mumbai",
    group: "align",
    marker: { xPct: 60, yPct: 49 },
  },
  {
    id: "peninsula-business-park",
    title: "Align by DBSW, Peninsula Business park",
    image: "/images/location/map_listing/listing_mapstate.webp",
    address: "Peninsula Business Park, Lower Parel, Mumbai 400013",
    phone: "02240779100",
    city: "mumbai",
    group: "align",
    marker: { xPct: 56, yPct: 73 },
  },
];

